# Generated by Django 5.0.6 on 2024-05-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationdata",
            name="name",
        ),
        migrations.RemoveField(
            model_name="simulationdata",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="simulationdata",
            name="value",
        ),
        migrations.AddField(
            model_name="simulationdata",
            name="angle",
            field=models.FloatField(default=40),
        ),
        migrations.AddField(
            model_name="simulationdata",
            name="cwArho",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="simulationdata",
            name="height",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="simulationdata",
            name="mass",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="simulationdata",
            name="velocity",
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name="simulationdata",
            name="xmax",
            field=models.FloatField(default=6),
        ),
        migrations.AddField(
            model_name="simulationdata",
            name="ymax",
            field=models.FloatField(default=4),
        ),
    ]
