# Generated by Django 5.0.6 on 2024-05-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0002_remove_simulationdata_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationdata",
            name="angle",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="simulationdata",
            name="cwArho",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="simulationdata",
            name="height",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="simulationdata",
            name="mass",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="simulationdata",
            name="velocity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="simulationdata",
            name="xmax",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="simulationdata",
            name="ymax",
            field=models.FloatField(),
        ),
    ]
