# Generated by Django 5.0.6 on 2024-05-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0003_alter_simulationdata_angle_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simulationdata",
            old_name="cwArho",
            new_name="c_F",
        ),
    ]
